### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by warut-vijit** [acm-uiuc/twilight#14]
Integrate user defined filters into `plugin_manager.py` to alter plug-ins at runtime with a priority queue

**Comment by warut-vijit** [comment]
Should plugins be persistent by default? On the one hand, the priority queue might get unnecessarily long if it is not regularly pruned, but on the other hand, re-adding filters might get tedious. A possible compromise between these might be to have them be persistent, but provide an endpoint for removing them from the queue

**Comment by wchill** [comment]
Filters should always be persistent and apply to all plugins unless disabled.

**Comment by wchill** [comment]
Closed by #19
